name: dgdm-histopath
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  
  # PyTorch with CUDA support
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - pandas>=1.3.0
  
  # Image processing
  - pillow>=8.3.0
  - opencv>=4.5.0
  
  # Visualization
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  
  # Data handling
  - h5py>=3.1.0
  - pyyaml>=6.0
  - tqdm>=4.62.0
  
  # Development tools
  - jupyter
  - ipykernel
  - notebook
  
  # System dependencies for OpenSlide
  - openslide
  
  # Install remaining dependencies via pip
  - pip
  - pip:
    - torch-geometric>=2.3.0
    - pytorch-lightning>=2.0.0
    - openslide-python>=1.1.2
    - albumentations>=1.3.0
    - timm>=0.9.0
    - transformers>=4.20.0
    - wandb>=0.15.0
    - tensorboard>=2.8.0
    - hydra-core>=1.3.0
    - omegaconf>=2.3.0
    - typer>=0.9.0
    - rich>=13.0.0
    - pydantic>=2.0.0
    - joblib>=1.1.0
    - pytest>=7.0.0
    - pytest-cov>=4.0.0
    - black>=22.0.0
    - flake8>=5.0.0
    - mypy>=1.0.0